apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-mysql
  spec:
    storageClassName: efs-class
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteMany
    nfs:
      server: us-west-2a.fs-xxxxxx.efs.us-west-2.amazonaws.com
      path: "/"

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-mysql
  spec:
    storageClassName: efs-class
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    volumeName: pv-mysql
